spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soe?serverTimezone=UTC
    username: root
    password: 123

  mail:
    host: smtp.qq.com
    username: soe-irene@qq.com
    password: rmkhituvhrhdeggd
    default-encoding: utf-8
    properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true
        mail.smtp.socketFactory.port: 465
        mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
        mail.smtp.socketFactory.fallback: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/irene/Mapper/MapperXml/*Mapper.xml
  type-aliases-package: com.irene.Entity
server:
  port: 443
  ssl:
    enabled: true
    key-store:  classpath:ssl/irene.icemomo.com.jks
    key-store-password: z19w1omc2s24t19
    keyStoreType: JKS





qiniu:
  accessKey: vuPRvtpTUVkqRJ2wRHgMpwIO8Irr-Q5mPJoY6p97v
  secretKey: 8nUE6KM_7DbYxemVwo7LpWgZCG8AxeIL5hbK5FZB
  bucketName: irene-soe  #存储空间名称
  path: https://soe.icemomo.com

